# Generated by Django 6.0.3 on 2026-03-27 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders2', '0003_initial'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
